import { test, before, after } from 'node:test'
import assert from 'node:assert/strict'
import { BASE, startApp, stopApp, newPage, bodyText } from './helpers.mjs'

let browser
before(async () => { browser = await startApp() })
after(async () => { await stopApp(browser) })

const submit = (page, scope = 'form') => page.click(`${scope} button[type=submit]`)

test('signup: validates, then navigates to /app', async () => {
    const page = await newPage(browser)
    await page.goto(BASE + '/auth/signup', { waitUntil: 'networkidle' })
    await submit(page)
    assert.match(await bodyText(page), /required|مطلوب/i)
    const inputs = page.locator('form input:not([type=checkbox]):not([type=hidden])')
    const names = await inputs.evaluateAll((els) => els.map((e) => e.name || e.id || e.type))
    const fill = async (re, v) => { const i = names.findIndex((n) => re.test(n)); if (i >= 0) await inputs.nth(i).fill(v) }
    await fill(/name/i, 'Osama Hattab'); await fill(/phone/i, '0791234567'); await fill(/email/i, 'osama@example.com')
    await fill(/^password$/i, 'Passw0rd!x'); await fill(/confirm/i, 'Different1!')
    await submit(page)
    assert.ok(page.url().endsWith('/auth/signup'), 'mismatched passwords must block')
    await fill(/confirm/i, 'Passw0rd!x')
    await submit(page)
    assert.ok(page.url().endsWith('/auth/signup'), 'terms must be accepted')
    await page.locator('form input[type=checkbox]').first().check({ force: true })
    await submit(page)
    await page.waitForURL(/\/app/)
    assert.deepEqual(page.errors, [])
})

test('login: disabled when empty, bad credentials rejected, org role navigates', async () => {
    const page = await newPage(browser)
    await page.goto(BASE + '/auth/login', { waitUntil: 'networkidle' })
    assert.ok(await page.locator('form button[type=submit]').isDisabled())
    await page.fill('#identifier', 'error@example.com')
    await page.fill('input[type=password]', 'abcdefgh')
    await submit(page)
    await page.waitForTimeout(300)
    assert.ok(page.url().endsWith('/auth/login'))
    await page.goto(BASE + '/auth/login', { waitUntil: 'networkidle' })
    await page.locator('[role=radio]').nth(1).click()
    await page.fill('#identifier', 'org@example.com')
    await page.fill('input[type=password]', 'Passw0rd!x')
    await submit(page)
    await page.waitForURL(/\/org\/dashboard/)
    assert.deepEqual(page.errors, [])
})

test('forgot password: rejects bad email, confirms good one', async () => {
    const page = await newPage(browser)
    await page.goto(BASE + '/auth/forgot-password', { waitUntil: 'networkidle' })
    await page.fill('form input', 'not-an-email@')
    await submit(page)
    await page.waitForTimeout(300)
    const bad = await bodyText(page)
    await page.fill('form input', 'osama@example.com')
    await submit(page)
    await page.waitForTimeout(1800)
    assert.notEqual(await bodyText(page), bad)
    assert.deepEqual(page.errors, [])
})

test('contact: validates, sends, clears the form', async () => {
    const page = await newPage(browser)
    await page.goto(BASE + '/contact', { waitUntil: 'networkidle' })
    await submit(page, '.contact-form')
    assert.ok(await page.locator('.contact-form [class*=error], .contact-form [aria-invalid=true]').count() > 0)
    const fields = page.locator('.contact-form input:not([type=hidden]), .contact-form textarea')
    const kinds = await fields.evaluateAll((els) => els.map((e) => e.type))
    for (let i = 0; i < kinds.length; i++) await fields.nth(i).fill(kinds[i] === 'email' ? 'osama@example.com' : 'Hello there')
    await submit(page, '.contact-form')
    await page.waitForTimeout(1600)
    assert.ok((await fields.evaluateAll((els) => els.map((e) => e.value))).every((v) => v === ''))
})

test('create event wizard: validation, draft, publish', async () => {
    const page = await newPage(browser)
    await page.goto(BASE + '/org/create-event', { waitUntil: 'networkidle' })
    await page.evaluate(() => localStorage.clear())
    await page.reload({ waitUntil: 'networkidle' })
    await page.click('#wizard-next')
    assert.equal(await page.locator('#wizard-back').count(), 0, 'empty step 1 must block')
    await page.fill('[name=title]', 'Test Hackathon 2027')
    await page.fill('[name=startDate]', '2027-03-10')
    await page.fill('[name=endDate]', '2027-03-01')
    await page.fill('[name=description]', 'A great event')
    await page.click('#wizard-next')
    assert.equal(await page.locator('#wizard-back').count(), 0, 'end before start must block')
    await page.fill('[name=endDate]', '2027-03-12')
    await page.click('#wizard-next')
    assert.match(await bodyText(page), /Test Hackathon 2027/)
    await page.click('#wizard-draft')
    await page.reload({ waitUntil: 'networkidle' })
    assert.equal(await page.inputValue('[name=title]'), 'Test Hackathon 2027')
    await page.click('#wizard-next')
    await page.click('#wizard-next')
    await page.click('#wizard-publish')
    await page.waitForURL(/org\/dashboard/)
    assert.deepEqual(page.errors, [])
})

test('participant profile: edit dialog validates, saves, persists', async () => {
    const page = await newPage(browser)
    await page.goto(BASE + '/app/profile', { waitUntil: 'networkidle' })
    await page.evaluate(() => localStorage.removeItem('eventify:participant-profile'))
    await page.reload({ waitUntil: 'networkidle' })
    await page.getByRole('button', { name: 'Edit Profile' }).first().click()
    const dialog = page.getByRole('dialog')
    await dialog.getByLabel('Name').fill('   ')
    await dialog.getByRole('button', { name: 'Save' }).click()
    assert.match(await dialog.innerText(), /Name is required/)
    await dialog.getByLabel('Name').fill('Osama')
    await dialog.getByLabel('Headline').fill('Frontend Developer')
    await dialog.getByLabel(/Skills/).fill('React, CSS')
    await dialog.getByRole('button', { name: 'Save' }).click()
    assert.equal(await page.getByRole('dialog').count(), 0)
    await page.reload({ waitUntil: 'networkidle' })
    const text = await bodyText(page)
    assert.match(text, /Osama/)
    assert.match(text, /Frontend Developer/)
    assert.match(text, /React/)
    assert.deepEqual(page.errors, [])
})

test('participant profile: add project / experience, translucent backdrop, scrolling', async () => {
    const page = await newPage(browser)
    await page.setViewportSize({ width: 1280, height: 600 })
    await page.goto(BASE + '/app/profile', { waitUntil: 'networkidle' })
    await page.evaluate(() => localStorage.removeItem('eventify:participant-profile'))
    await page.reload({ waitUntil: 'networkidle' })
    await page.getByRole('button', { name: 'Add project' }).first().click()
    const dialog = page.getByRole('dialog')
    const backdrop = dialog.locator('xpath=..')
    const style = await backdrop.evaluate((el) => ({ bg: getComputedStyle(el).backgroundColor, blur: getComputedStyle(el).backdropFilter }))
    assert.match(style.bg, /(rgba\(0, 0, 0, |oklab\(0 0 0 \/ )0?\.\d+/, 'backdrop must be translucent')
    assert.match(style.blur, /blur/)
    assert.equal(await page.evaluate(() => document.body.style.overflow), 'hidden', 'page behind must not scroll')
    assert.ok(await dialog.locator('[data-edit-body]').evaluate((el) => el.scrollHeight > el.clientHeight), 'dialog body must scroll on a short screen')
    const cancel = dialog.getByRole('button', { name: 'Cancel' })
    const box = await cancel.boundingBox()
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
    await page.mouse.down()
    await page.waitForTimeout(300)
    assert.notEqual(await cancel.evaluate((el) => getComputedStyle(el).transform), 'none', 'pressed button must visibly change')
    await page.mouse.move(5, 5)
    await page.mouse.up()
    await dialog.getByLabel('Project 3 Title').fill('My Graduation Project')
    await dialog.getByLabel('Project 3 Description').fill('Built with React')
    await dialog.getByRole('button', { name: /Add experience/ }).click()
    await dialog.getByLabel('Experience 3 Title').fill('Frontend Intern')
    await dialog.getByRole('button', { name: 'Remove this project' }).first().click()
    await dialog.getByRole('button', { name: 'Save' }).click()
    assert.equal(await page.evaluate(() => document.body.style.overflow), '', 'scroll restored after closing')
    await page.reload({ waitUntil: 'networkidle' })
    const text = await bodyText(page)
    assert.match(text, /My Graduation Project/)
    assert.match(text, /Frontend Intern/)
    assert.doesNotMatch(text, /NeuralMesh/)
    assert.deepEqual(page.errors, [])
})
