module.exports = {
    common: {
        required: 'هذا الحقل مطلوب.',
        invalidEmail: 'الرجاء إدخال بريد إلكتروني صحيح.',
        invalidPhone: 'الرجاء إدخال رقم هاتف صحيح.',
        invalidUrl: 'الرجاء إدخال رابط صحيح.',
        secureAccess: 'دخول آمن',
        showPassword: 'إظهار كلمة المرور',
        or: 'أو',
        continueGoogle: 'المتابعة عبر Google',
        and: 'و',
    },
    login: {
        visualBadge: 'سريع، آمن، بسيط',
        visualTitle: 'الفرصة المناسبة، للشخص المناسب، في الوقت المناسب.',
        visualDesc: 'انضم إلى آلاف الطلاب والمحترفين المكتشفين لمسابقات ودورات وفعاليات تطابق مهاراتهم.',
        visualPoint1: 'تسجيل دخول مدعوم بالبريد أو الهاتف',
        visualPoint2: 'وصول سريع لما حفظته مسبقًا',
        invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة. الرجاء التحقق من بياناتك والمحاولة مجددًا.',
        title: 'أهلاً بعودتك',
        subtitle: 'سجّل الدخول ببريدك الإلكتروني أو رقم هاتفك لمتابعة اكتشاف الفرص المناسبة لك.',
        identifierLabel: 'البريد الإلكتروني أو الهاتف',
        identifierPlaceholder: 'you@example.com أو +962 7XXXXXXXX',
        passwordLabel: 'كلمة المرور',
        rememberMe: 'تذكرني',
        forgotPassword: 'نسيت كلمة المرور؟',
        submit: 'تسجيل الدخول',
        submitting: 'جارٍ تسجيل الدخول...',
        noAccount: 'ليس لديك حساب؟',
        createAccount: 'إنشاء حساب',
    },
    forgotPassword: {
        visualTitle: 'حسابك، يعود إليك بأمان.',
        visualDesc: 'سنرسل لك رابطًا آمنًا وله صلاحية محدودة. بدون أسئلة أمنية، بدون تعقيد — فقط اضغط وحدد كلمة مرور جديدة.',
        visualPoint1: 'روابط إعادة التعيين تنتهي بعد 30 دقيقة',
        visualPoint2: 'كلمة مرورك لا تُرسل عبر البريد أبدًا',
        backToLogin: 'العودة لتسجيل الدخول',
        badge: 'استعادة كلمة المرور',
        title: 'نسيت كلمة المرور؟',
        subtitle: 'لا مشكلة — أدخل البريد الإلكتروني أو رقم الهاتف المرتبط بحسابك وسنرسل لك رابط إعادة التعيين.',
        submitting: 'جارٍ الإرسال...',
        submit: 'إرسال رابط إعادة التعيين',
        remembered: 'تذكرتها في النهاية؟',
        logIn: 'تسجيل الدخول',
        checkInboxTitle: 'تحقق من بريدك الوارد',
        checkInboxDesc1: 'إذا كان هناك حساب مطابق لـ',
        checkInboxDesc2: 'فرابط إعادة تعيين كلمة المرور في طريقه إليك. يبقى الرابط صالحًا لمدة 30 دقيقة.',
        thatEmail: 'ذلك البريد',
        resending: 'جارٍ إعادة الإرسال...',
        resend: 'إعادة إرسال الرابط',
    },
    signup: {
        visualLive: 'متاح الآن',
        visualTitle: 'اكتشف. تواصل. انمُ.',
        visualDesc: 'أنشئ ملفك الشخصي، ودع الذكاء الاصطناعي يولّد سيرتك الذاتية، وافتح مسابقات ودورات وفعاليات مطابقة لك.',
        mockHackathon: 'هاكاثون',
        mockDaysLeft: 'يومان متبقيان',
        mockEventTitle: 'هاكاثون الذكاء الاصطناعي العالمي 2026',
        mockEventDesc: 'ابنِ الجيل القادم من أنظمة الذكاء الاصطناعي الوكيلة.',
        mockJoinTeam: 'انضم لفريق',
        mockAiTitle: 'موائم الذكاء الاصطناعي',
        mockAiDesc: '3 فعاليات تطابق تفاصيل سيرتك الذاتية تمامًا.',
        visualSupport: 'الدعم',
        title: 'أنشئ حسابك',
        subtitlePersonal: 'أنشئ حسابك الشخصي لتبدأ استكشاف الفرص.',
        subtitleOrg: 'أكمل تسجيل جهتك المنظمة بالتحقق من بياناتها.',
        personalAccount: 'حساب شخصي',
        personalAccountDesc: 'ابحث عن فرص',
        organizationAccount: 'حساب جهة منظمة',
        organizationAccountDesc: 'انشر فعاليات',
        orgNameLabel: 'اسم الجهة المنظمة *',
        orgNamePlaceholder: 'مثال: TechGenius Labs',
        fullNameLabel: 'الاسم الكامل *',
        fullNamePlaceholder: 'سارة أحمد',
        phoneLabel: 'رقم الهاتف *',
        websiteLabel: 'الموقع الإلكتروني',
        optional: 'اختياري',
        workEmailLabel: 'البريد الإلكتروني الرسمي *',
        emailLabel: 'البريد الإلكتروني *',
        passwordLabel: 'كلمة المرور *',
        passwordPlaceholder: '8 أحرف على الأقل',
        passwordTooShort: 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.',
        passwordMismatch: 'كلمتا المرور غير متطابقتين.',
        strengthLabel: 'القوة:',
        strength: { weak: 'ضعيفة', medium: 'متوسطة', strong: 'قوية' },
        confirmPasswordLabel: 'تأكيد كلمة المرور *',
        confirmPasswordPlaceholder: 'أعد إدخال كلمة المرور',
        agreeTo: 'أوافق على',
        submitting: 'جارٍ الإنشاء...',
        submitOrg: 'المتابعة إلى التوثيق',
        submitPersonal: 'إنشاء حساب',
        haveAccount: 'لديك حساب بالفعل؟',
    },
    orgVerification: {
        title: 'توثيق الجهة المنظمة',
        subtitle: 'أكمل توثيق جهتك المنظمة لتتمكن من نشر الفعاليات.',
        stepAccountCreated: 'تم إنشاء الحساب',
        stepOf: 'الخطوة 2 من 2',
        orgInfoTitle: 'معلومات الجهة المنظمة',
        orgType: 'نوع الجهة',
        selectType: 'اختر النوع',
        typeUniversity: 'جامعة',
        typeCompany: 'شركة',
        typeNgo: 'جمعية غير ربحية',
        typeGovernment: 'جهة حكومية',
        typeStartup: 'شركة ناشئة',
        typeOther: 'أخرى',
        website: 'الموقع الإلكتروني',
        phone: 'رقم الهاتف',
        country: 'الدولة',
        city: 'المدينة',
        repTitle: 'الممثل المخوَّل',
        repName: 'الاسم الكامل',
        jobTitle: 'المسمى الوظيفي',
        docsTitle: 'وثائق التوثيق',
        uploadTitle: 'ارفع وثيقة التوثيق',
        uploadDesc: 'السجل التجاري، رخصة، خطاب جامعي، أو أي وثيقة رسمية أخرى.',
        descTitle: 'وصف الجهة المنظمة',
        descPlaceholder: 'أخبرنا عن جهتك المنظمة، الفعاليات التي تنظمها، أهدافك، ومن هو جمهورك...',
        confirmAccurate: 'أؤكد أن جميع المعلومات المقدَّمة دقيقة.',
        confirmReview: 'أوافق على أن تراجع EVENTIFY الوثائق المقدَّمة قبل تفعيل حساب جهتي المنظمة.',
        back: 'رجوع',
        submit: 'إرسال للتوثيق',
    },
    orgPending: {
        title: 'تم إنشاء الحساب بنجاح',
        thankYou: 'شكرًا لتسجيل جهتك المنظمة لدى',
        created: 'تم إنشاء حساب جهتك المنظمة بنجاح. هو الآن قيد المراجعة من قبل فريق الإدارة لدينا.',
        emailNotice: 'بمجرد الموافقة على حسابك، سنرسل بريدًا إلكترونيًا إلى عنوانك المسجَّل لتفعيل حسابك والبدء بنشر الفعاليات.',
        redirecting: 'جارٍ التحويل إلى الصفحة الرئيسية خلال',
        secondsSuffix: 'ثانية...',
        goHome: 'الذهاب للرئيسية',
    },
}
