module.exports = {
    common: {
        required: 'This field is required.',
        invalidEmail: 'Please enter a valid email address.',
        invalidPhone: 'Please enter a valid phone number.',
        invalidUrl: 'Please enter a valid URL.',
        secureAccess: 'Secure Access',
        showPassword: 'Show password',
        or: 'OR',
        continueGoogle: 'Continue with Google',
        and: 'and',
    },
    login: {
        visualBadge: 'Fast, secure, simple',
        visualTitle: 'The right opportunity, for the right person, at the right time.',
        visualDesc: 'Join thousands of students and professionals discovering competitions, courses, and events matched to their skills.',
        visualPoint1: 'Email or phone login supported',
        visualPoint2: 'Quick access to your saved work',
        invalidCredentials: 'Invalid email or password. Please check your credentials and try again.',
        title: 'Welcome back',
        subtitle: 'Log in with your email or phone number to keep discovering opportunities tailored to you.',
        identifierLabel: 'Email or Phone',
        identifierPlaceholder: 'you@example.com or +1 555 123 4567',
        passwordLabel: 'Password',
        rememberMe: 'Remember me',
        forgotPassword: 'Forgot password?',
        submit: 'Sign In',
        submitting: 'Logging in...',
        noAccount: "Don't have an account?",
        createAccount: 'Create Account',
    },
    forgotPassword: {
        visualTitle: 'Your account, safely back in your hands.',
        visualDesc: "We'll email you a secure, time-limited link. No security questions, no hassle — just click and set a new password.",
        visualPoint1: 'Reset links expire after 30 minutes',
        visualPoint2: 'Your password is never sent by email',
        backToLogin: 'Back to log in',
        badge: 'Password Recovery',
        title: 'Forgot your password?',
        subtitle: "No worries — enter the email or phone number linked to your account and we'll send you a reset link.",
        submitting: 'Sending...',
        submit: 'Send Reset Link',
        remembered: 'Remembered it after all?',
        logIn: 'Log in',
        checkInboxTitle: 'Check your inbox',
        checkInboxDesc1: 'If an account matches',
        checkInboxDesc2: 'a password reset link is on its way. The link stays valid for 30 minutes.',
        thatEmail: 'that email',
        resending: 'Resending...',
        resend: 'Resend link',
    },
    signup: {
        visualLive: 'Now Live',
        visualTitle: 'Discover. Connect. Grow.',
        visualDesc: 'Create your profile, let AI generate your CV, and unlock competitions, courses, and events matched to you.',
        mockHackathon: 'Hackathon',
        mockDaysLeft: '2 days left',
        mockEventTitle: 'Global AI Hackathon 2026',
        mockEventDesc: 'Build the next generation of agentic AI systems.',
        mockJoinTeam: 'Join Team',
        mockAiTitle: 'AI Matchmaker',
        mockAiDesc: '3 events perfectly fit your resume details.',
        visualSupport: 'Support',
        title: 'Create your account',
        subtitlePersonal: 'Create your personal account to start exploring opportunities.',
        subtitleOrg: "Complete your organization registration by verifying your organization details.",
        personalAccount: 'Personal Account',
        personalAccountDesc: 'Find opportunities',
        organizationAccount: 'Organization Account',
        organizationAccountDesc: 'Publish events',
        orgNameLabel: 'Organization Name *',
        orgNamePlaceholder: 'e.g. TechGenius Labs',
        fullNameLabel: 'Full Name *',
        fullNamePlaceholder: 'Sarah Chen',
        phoneLabel: 'Phone Number *',
        websiteLabel: 'Website',
        optional: 'optional',
        workEmailLabel: 'Work Email *',
        emailLabel: 'Email Address *',
        passwordLabel: 'Password *',
        passwordPlaceholder: 'At least 8 characters',
        passwordTooShort: 'Password must be at least 8 characters.',
        passwordMismatch: 'Passwords do not match.',
        strengthLabel: 'Strength:',
        strength: { weak: 'Weak', medium: 'Medium', strong: 'Strong' },
        confirmPasswordLabel: 'Confirm Password *',
        confirmPasswordPlaceholder: 'Re-enter your password',
        agreeTo: 'I agree to the',
        submitting: 'Creating...',
        submitOrg: 'Continue to Verification',
        submitPersonal: 'Create Account',
        haveAccount: 'Already have an account?',
    },
    orgVerification: {
        title: 'Organization Verification',
        subtitle: "Complete your organization's verification to publish events.",
        stepAccountCreated: 'Account Created',
        stepOf: 'Step 2 of 2',
        orgInfoTitle: 'Organization Information',
        orgType: 'Organization Type',
        selectType: 'Select Type',
        typeUniversity: 'University',
        typeCompany: 'Company',
        typeNgo: 'NGO',
        typeGovernment: 'Government',
        typeStartup: 'Startup',
        typeOther: 'Other',
        website: 'Website',
        phone: 'Phone Number',
        country: 'Country',
        city: 'City',
        repTitle: 'Authorized Representative',
        repName: 'Full Name',
        jobTitle: 'Job Title',
        docsTitle: 'Verification Documents',
        uploadTitle: 'Upload Verification Document',
        uploadDesc: 'Commercial Registration, License, University Letter or any official document.',
        descTitle: 'Organization Description',
        descPlaceholder: 'Tell us about your organization, the events you organize, your goals, and who your audience is...',
        confirmAccurate: 'I confirm that all submitted information is accurate.',
        confirmReview: 'I agree that EVENTIFY may review my submitted documents before activating my organization account.',
        back: 'Back',
        submit: 'Submit for Verification',
    },
    orgPending: {
        title: 'Account Created Successfully',
        thankYou: 'Thank you for registering your organization with',
        created: 'Your organization account has been created successfully. It is currently under review by our administration team.',
        emailNotice: "Once your account is approved, we'll send an email to your registered address so you can activate your account and start publishing events.",
        redirecting: 'Redirecting to the home page in',
        secondsSuffix: 'seconds...',
        goHome: 'Go to home',
    },
}
