module.exports = {
    tag: 'Legal',
    privacyTitle: 'Privacy policy',
    privacyIntro: 'What we collect, why we collect it, and what you can do about it — in plain language.',
    termsTitle: 'Terms of service',
    termsIntro: 'The rules for using EVENTIFY, for students and for the organizations publishing on it.',
    updated: 'Last updated 4 September 2026',
    contactForm: 'contact form',
    privacy: {
        h1: 'What we collect',
        p1: 'Two kinds of data. First, what you give us: your name, email, university or organization, the skills on your profile, the files you attach to an application, and the messages you send us. Second, what your use of the platform produces: which opportunities you open, save and apply to, and the match scores generated from your profile.',
        h2: 'Why we collect it',
        p2li1: 'To match you with opportunities. Without your skills and level, a match score is meaningless.',
        p2li2: 'To pass your application to the organization you applied to. They see the profile and files you submitted, nothing else.',
        p2li3: 'To notify you before a deadline closes on something you saved.',
        p2li4: 'To review organizations before they can publish, which is how listings stay real.',
        h3: 'What we do not do',
        p3: 'We do not sell your data. We do not pass your profile to organizations you have not applied to. We do not use the content of your applications to train models.',
        h4: 'Who can see your profile',
        p4: 'Your public profile is visible to other EVENTIFY users and to verified organizations. Your email, phone number and attached files are shared only with an organization you have applied to, and only after you submit that application.',
        h5: 'Keeping data',
        p5: 'Application records stay for as long as your account is open, so you can see your own history. Delete your account and the profile, files and application history are removed within 30 days. Aggregate counts that cannot identify you — such as how many people applied to an event — remain with the organization.',
        h6: 'Your controls',
        p6li1: 'Edit or remove anything on your profile at any time from your settings.',
        p6li2: 'Request a copy of your data, or its deletion, by writing to hello@eventify.io.',
        p6li3: 'Turn deadline and status notifications off without closing your account.',
        h7: 'Cookies',
        p7: 'We use one functional cookie to keep you signed in and a local preference for your light or dark theme. No advertising or cross-site tracking cookies are set.',
        h8: 'Questions',
        p8: 'Write to hello@eventify.io or use the',
        p8b: 'We answer within one working day.',
    },
    terms: {
        h1: 'Who can use EVENTIFY',
        p1: 'Anyone aged 16 or over can create a student account. Organization accounts are created by someone authorized to represent that organization, and are usable only after our review team verifies it.',
        h2: 'Your account',
        p2: 'Keep your password to yourself and your profile accurate. You are responsible for what happens under your account. Applications submitted from your account are treated as submitted by you.',
        h3: 'What we expect from students',
        p3li1: 'Represent your own skills and history honestly. Fabricated profiles get suspended.',
        p3li2: "Do not submit someone else's work, CV or certificates as your own.",
        p3li3: 'Do not scrape, resell or republish listings from the platform.',
        h4: 'What we expect from organizations',
        p4li1: 'Publish only opportunities that exist, with accurate dates, requirements and prizes.',
        p4li2: 'Use applicant data solely to assess that application.',
        p4li3: 'Charging students to apply is not permitted, and neither is asking for payment details on EVENTIFY.',
        h5: 'Review and removal',
        p5: 'Every opportunity is reviewed before it goes live. We can decline or remove a listing that is incomplete, misleading or unsafe, and we can suspend an account that breaks these terms. Where the situation allows it, we tell you why and how to appeal.',
        h6: 'Content you post',
        p6: 'You keep ownership of everything you upload. You give us permission to display it on EVENTIFY for the purpose you uploaded it for — a profile shown to organizations you applied to, or a listing shown to students.',
        h7: 'What EVENTIFY does not guarantee',
        p7: 'We connect students and organizations. We do not run the events themselves and cannot guarantee an outcome, a prize, a placement or the conduct of an organizer. Match scores are a ranking aid, not a promise.',
        h8: 'Changes',
        p8: 'If these terms change materially, we notify account holders before the change takes effect. Continuing to use EVENTIFY after that date means the new terms apply.',
        h9: 'Contact',
        p9: 'Questions about these terms go to hello@eventify.io.',
    },
}
